name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.3 # Dart SDK version
  flutter: ^3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter
                                                                                              
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  bloc_test: ^9.1.3
  mockito: ^5.4.2
  equatable: ^2.0.5
  flutter_screenutil: ^5.8.4
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
flutter:
  assets:
    - assets/images/
  uses-material-design: true
